// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Apigateway.Inputs
{

    public sealed class EventHandlerRouteArgs : Pulumi.ResourceArgs
    {
        [Input("function")]
        public Input<Pulumi.Aws.Lambda.Function>? Function { get; set; }

        [Input("method")]
        public Input<string>? Method { get; set; }

        [Input("path")]
        public Input<string>? Path { get; set; }

        public EventHandlerRouteArgs()
        {
        }
    }
}
