// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

import * as aws from "@pulumi/aws";

export class RestAPI extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'apigateway:index:RestAPI';

    /**
     * Returns true if the given object is an instance of RestAPI.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RestAPI {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RestAPI.__pulumiType;
    }

    public /*out*/ readonly api!: pulumi.Output<aws.apigateway.RestApi>;
    public /*out*/ readonly url!: pulumi.Output<string>;

    /**
     * Create a RestAPI resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RestAPIArgs, opts?: pulumi.ComponentResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.routes === undefined) && !opts.urn) {
                throw new Error("Missing required property 'routes'");
            }
            inputs["routes"] = args ? args.routes : undefined;
            inputs["api"] = undefined /*out*/;
            inputs["url"] = undefined /*out*/;
        } else {
            inputs["api"] = undefined /*out*/;
            inputs["url"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(RestAPI.__pulumiType, name, inputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a RestAPI resource.
 */
export interface RestAPIArgs {
    readonly routes: pulumi.Input<pulumi.Input<inputs.EventHandlerRoute>[]>;
}
